### ISSUE TITLE
update vue peerDependencies

### ISSUE THREAD

**Issue by huluobotx** [jd-solanki/anu#223]
The ant-vue package use "vue": "3.3.4", if i update vue version in my project，it build fail

**Comment by huluobotx** [comment]
update vue 3.3.11 can build success

**Comment by huluobotx** [comment]
the error is:
```
TypeError: Cannot read properties of null (reading 'setupContext')
    at getContext (\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2447:12)
    at useSlots (\node_modules\.pnpm\@vue+runtime-core@3.3.4\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:2414:10)
    at file:///D:/work/code/other/ssg/xsg/node_modules/.pnpm/anu-vue@0.15.2_@unocss+reset@0.41.2_@vueuse+core@10.7.0_vue-router@4.2.5/node_modules/anu-vue/dist/anu-vue.js:1741:13
    at Proxy.<anonymous> (file:///D:/work/code/other/ssg/xsg/node_modules/.pnpm/anu-vue@0.15.2_@unocss+reset@0.41.2_@vueuse+core@10.7.0_vue-router@4.2.5/node_modules/anu-vue/dist/anu-vue.js:2088:18)
    at renderComponentRoot (\node_modules\.pnpm\@vue+runtime-core@3.3.11\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:417:16)
    at renderComponentSubTree (\node_modules\.pnpm\@vue+server-renderer@3.3.11_vue@3.3.11\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:442:28)
    at renderComponentVNode (\node_modules\.pnpm\@vue+server-renderer@3.3.11_vue@3.3.11\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:371:12)
    at ssrRenderComponent (\node_modules\.pnpm\@vue+server-renderer@3.3.11_vue@3.3.11\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:86:10)
```
