### ISSUE TITLE
`presetThemeDefault`: Cannot use shortcutOverrides option

### ISSUE THREAD

**Issue by brojor** [jd-solanki/anu#41]
In version 0.8.0 and higher we lost the ability to override shortcuts from presetThemeDefault.
If we use shortcutOverrides option like this:
```js
presetThemeDefault({
  shortcutOverrides: {
    btn: 'px-[0.75em] py-[0.375em] rounded-[0.375em] gap-x-[0.375em] whitespace-nowrap',
  },
})
```
it will raise this error
```
[vite] Internal server error: result.flatMap is not a function
      at UnoGenerator.expandShortcut (/Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/@unocss+core@0.45.28/node_modules/@unocss/core/dist/index.cjs:817:14)
      at UnoGenerator.parseToken (/Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/@unocss+core@0.45.28/node_modules/@unocss/core/dist/index.cjs:497:27)
      at /Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/@unocss+core@0.45.28/node_modules/@unocss/core/dist/index.cjs:524:34
      at Array.map (<anonymous>)
      at UnoGenerator.generate (/Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/@unocss+core@0.45.28/node_modules/@unocss/core/dist/index.cjs:521:46)
      at Context.load (/Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/@unocss+vite@0.45.28_vite@3.1.6/node_modules/@unocss/vite/dist/index.cjs:502:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.load (file:///Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/vite@3.1.6/node_modules/vite/dist/node/chunks/dep-db16f19c.js:41084:32)
      at async loadAndTransform (file:///Users/brojor/dev/testing/anu-9.1-test/node_modules/.pnpm/vite@3.1.6/node_modules/vite/dist/node/chunks/dep-db16f19c.js:37312:24)
```

**Comment by jd-solanki** [comment]
Hi 👋🏻

Docs needs update, if you look at the source [file](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/presets/theme-default/index.ts) `btn` is not `a-btn`.

Try below and let me know:
```ts
shortcutOverrides: {
  'a-btn': 'px-[1.75em] py-[0.375em] rounded-[0.375em] gap-x-[0.375em] whitespace-nowrap',
},
```

**Comment by brojor** [comment]
I used an example from the documentation just for the purpose of the issue. I actually need to override `a-base-input-root`. It worked fine until version 0.7.2. In later ones it raises this error until I comment out shortcutOverrides.

**Comment by jd-solanki** [comment]
I guess this is because we are no longer using object syntax for shortcuts. It's now array.

Need to dig shortcut options deeper in UnoCSS.

**Comment by brojor** [comment]
You mean like this ? 
```ts
shortcutOverrides: [
  {
    "a-btn": "px-[1.75em] py-[0.375em] rounded-[0.375em] gap-x-[0.375em] whitespace-nowrap",
  },
]
```
This gives me the same error.
Even this syntax doesn't work:
```ts
shortcutOverrides: [
  [/^a-btn$/, () => 'px-[1.75em] py-[0.375em] rounded-[0.375em] gap-x-[0.375em] whitespace-nowrap'],
]
```

**Comment by jd-solanki** [comment]
When this started we had object syntax and merging both objects did the job. However, with array value, we have to change how merging is performed.

ATM, I am working on `--a-spacing` feature. Once I am done with that I will resolve this issue.

**Comment by husayt** [comment]
@jd-solanki shall we keep this open until resolved?

**Comment by jd-solanki** [comment]
It's resolved now, you can try latest updates via edge releases: https://github.com/jd-solanki/anu/pull/114

Please give it a try and let me know 😇
